FROM node
LABEL authors="ITBear BV"
# update dependencies and install curl
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*
# Create app directory
WORKDIR /app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
# COPY package*.json ./ \
#     ./source ./

# This will copy everything from the source path 
# --more of a convenience when testing locally.
COPY . .
# update each dependency in package.json to the latest version
RUN npm run setup \
    npm install pm2 -g && pm2 install pm2-logrotate
# If you are building your code for production
RUN pm2 start server/server.js --name uptime-kuma
# Bundle app source
COPY . /app
EXPOSE 3001