# Simple docker-composer.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-monitor:
    image: maddemonoide/uptimemonitor:latest
    container_name: uptime-monitor
    volumes:
      - ./uptime-monitor:/app/data
    ports:
      - 3001:3001
    restart: always
