name: Docker Image Tags

on:
  push:
    tags: [ '*' ]
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push dockerhub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: philippdormann/uptime
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push ghcr
      uses: craftech-io/package-action@v3.1.0
      with:
        access_token: ${{ secrets.GHCR_TOKEN }}
        image_name: uptime
        # The desired tag for the image: latest + . Defaults to current branch or release version number.
        tags: |
          latest
          ${{ github.sha }}
          ${{ github.ref }}
